### ISSUE TITLE
qs_ prefix

### ISSUE THREAD

**Issue by sveinbjornt** [brentsimmons/QSKit#4]
The qs_ prefix is horrid and by itself, alone, prevents me from ever using this library.  What a truly terrible, non-Objective-C-esque idea!

**Comment by brentsimmons** [comment]
It’s Apple’s idea. Not mine.

https://developer.apple.com/library/ios/documentation/cocoa/conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html

Apple says to prefix category method names:

“In order to avoid undefined behavior, it’s best practice to add a prefix to method names in categories on framework classes, just like you should add a prefix to the names of your own classes. You might choose to use the same three letters you use for your class prefixes, but lowercase to follow the usual convention for method names, then an underscore, before the rest of the method name.”

Apple provides an example:

`+ (id)xyz_sortDescriptorWithKey:(NSString *)key ascending:(BOOL)ascending;`

Apple recommends three-letter prefixes, but I use just two. (Having to use three-letter-prefixes is a bit unfair. I'm sticking to two.)

**Comment by PadraigK** [comment]
Thanks so much for sharing all of this code. We're using parts of it in Castro already and plan to use more soon. 

I wanted to throw in an argument for removing the prefixes in spite of Apples recommendation. Aside from how it looks, it makes autocomplete less useful since we have to constantly remember that the category is a qs_ instead of just starting to type what we would expect the method to be called.
